export const MODES = [
  {
    id: 'explain',
    label: 'Explain Topic',
    icon: '📚',
    description: 'Understand complex concepts in simple language',
    placeholder: 'Ask me to explain any concept... e.g., "Explain recursion" or "What is machine learning?"',
    color: '#6366f1',
    examples: [
      'Explain the concept of recursion with examples',
      'What is machine learning and how does it work?',
      'Explain how TCP/IP protocol works',
      'What is Object-Oriented Programming?',
    ],
  },
  {
    id: 'exam',
    label: 'Exam Answer',
    icon: '📝',
    description: 'Generate structured university exam answers',
    placeholder: 'Enter a topic and specify the marks (2/5/10)... e.g., "Explain OSI model — 10 marks"',
    color: '#8b5cf6',
    examples: [
      'Explain the OSI model — 10 marks',
      'What is normalization in databases? — 5 marks',
      'Define an operating system — 2 marks',
      'Explain Dijkstra\'s algorithm with example — 10 marks',
    ],
  },
  {
    id: 'quiz',
    label: 'Quiz Generator',
    icon: '🧠',
    description: 'Test your knowledge with MCQ quizzes',
    placeholder: 'Enter a topic to generate MCQs... e.g., "Generate 5 MCQs on Data Structures"',
    color: '#ec4899',
    examples: [
      'Generate 5 MCQs on Data Structures',
      'Create a quiz on Python basics',
      'MCQ questions on Database Management',
      'Quiz on Operating System concepts',
    ],
  },
  {
    id: 'summary',
    label: 'Summarize Notes',
    icon: '📄',
    description: 'Turn long notes into concise summaries',
    placeholder: 'Paste your notes here and I\'ll summarize them with key takeaways...',
    color: '#10b981',
    examples: [
      'Summarize my notes on the Networking chapter',
      'Create key points from this lecture content...',
      'Summarize this textbook section for revision',
      'Convert these study notes into bullet points',
    ],
  },
  {
    id: 'code',
    label: 'Code Assistant',
    icon: '💻',
    description: 'Debug, explain, and improve your code',
    placeholder: 'Paste your code and describe what you need help with...',
    color: '#f59e0b',
    examples: [
      'Explain this Python code and find bugs',
      'Why is my C program crashing? [paste code]',
      'Improve this JavaScript function',
      'Write a SQL query to find duplicate records',
    ],
  },
  {
    id: 'chat',
    label: 'General Chat',
    icon: '💬',
    description: 'Ask me anything — your all-round AI companion',
    placeholder: 'Ask me anything...',
    color: '#06b6d4',
    examples: [
      'How do I study effectively for exams?',
      'What is the difference between RAM and ROM?',
      'Give me tips for time management as a student',
      'What career paths are there in Computer Science?',
    ],
  },
];
